package demo.demoproject.dao;

import demo.demoproject.entity.Userinfo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface UserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated
     */
    int insert(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated
     */
    Userinfo selectByPrimaryKey(Integer id);
    Userinfo selectByUser(String user,String pass);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated
     */
    List<Userinfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Userinfo record);

    //    登陆后显示所有用户信息
    Userinfo loginQuery(Userinfo userinfo);
    //	插入一条用户信息，返回状态
    int insertQuery(Userinfo userinfo);
}